version: '3.8'

services:

  # Service for the PostgreSQL database
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Service for the Ruby on Rails web application
  backend:
    build: .
    working_dir: /app/backend
    command: bundle exec CYPRESS=1 rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/backend
    depends_on:
      - db
      
# Define a volume for storing PostgreSQL data
volumes:
  postgres_data: